'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WS_Consulta_SAT
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Acuse", [Namespace]:="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Acuse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoEstatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoEstatus() As String
            Get
                Return Me.CodigoEstatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoEstatusField, value) <> true) Then
                    Me.CodigoEstatusField = value
                    Me.RaisePropertyChanged("CodigoEstatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WS_Consulta_SAT.IConsultaCFDIService")>  _
    Public Interface IConsultaCFDIService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConsultaCFDIService/Consulta", ReplyAction:="http://tempuri.org/IConsultaCFDIService/ConsultaResponse")>  _
        Function Consulta(ByVal expresionImpresa As String) As WS_Consulta_SAT.Acuse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IConsultaCFDIService/Consulta", ReplyAction:="http://tempuri.org/IConsultaCFDIService/ConsultaResponse")>  _
        Function ConsultaAsync(ByVal expresionImpresa As String) As System.Threading.Tasks.Task(Of WS_Consulta_SAT.Acuse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IConsultaCFDIServiceChannel
        Inherits WS_Consulta_SAT.IConsultaCFDIService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConsultaCFDIServiceClient
        Inherits System.ServiceModel.ClientBase(Of WS_Consulta_SAT.IConsultaCFDIService)
        Implements WS_Consulta_SAT.IConsultaCFDIService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Consulta(ByVal expresionImpresa As String) As WS_Consulta_SAT.Acuse Implements WS_Consulta_SAT.IConsultaCFDIService.Consulta
            Return MyBase.Channel.Consulta(expresionImpresa)
        End Function
        
        Public Function ConsultaAsync(ByVal expresionImpresa As String) As System.Threading.Tasks.Task(Of WS_Consulta_SAT.Acuse) Implements WS_Consulta_SAT.IConsultaCFDIService.ConsultaAsync
            Return MyBase.Channel.ConsultaAsync(expresionImpresa)
        End Function
    End Class
End Namespace
